all_dtf_subsites_english = {
"игры" : "games",
"индустрия" : "gameindustry",
"гость DTF" : "guest",
"gamedev" : "gamedev",
"кино и сериалы" : "cinema",
"жизнь" : "life",
"гайды" : "howto",
"почитать" : "read",
"железо" : "hard",
"цкидки" : "sale",
"инди" : "indie",
"ретро" : "retro",
"видео и гифки" : "avi",
"офтоп" : "flood",
"настолки" : "boardgames",
"подкасты" : "podcasts",
"киберспорт" : "esport",
"конкурс" : "contest",
"аниме" : "anime",
"вопросы" : "ask",
"мобайл" : "mobile",
"мемы" : "kek",
"no context" : "nocontext",
"наука" : "science",
"прямые эфиры" : "live",
"блогосфера" : "qat",
"музыка" : "music",
"творчество" : "craft",
"ссылки в интернете" : "nenanimalsia",
"жиза ГД" : "zhizagd",
"сломалось" : "bugs",
"ищу пати" : "party",
"батискаф подкаст" : "batiskaf",
"барахолка" : "barter",
"не занесли" : "nezanesli",
"скриншоты" : "screenshots",
"еverypod" : "everypod",
"о порно" : "aboutporn",
"шаурма и друзья" : "shaurmashaverma",
"unreal engine" : "unrealengine",
"фото" : "photo",
"rainbow six siege" : "r6",
"косплей" : "cosplay",
"unity" : "unity",
"арт" : "art",
"драма 24/7" : "dramaqueen",
"destiny" : "destiny",
"хокку и красивые коты" : "cats",
"коллекции" : "collection",
"киноликбез" : "narrative",
"мinecraft" : "minecraft",
"battlefield" : "bf",
"playStation" : "playstation",
"mordhau" : "mordhau",
"хакатон" : "hack",
"for Honor" : "forhonor",
"world of warcraft" : "wow",
"хакатон-2019" : "hackathon",
"анимация" : "animation",
"в предыдущих сериях" : "previous",
"тройное А" : "triplacast",
"глянец" : "gloss",
"новости геймдева" : "gamedevnews",
"игры star wars" : "starwars",
"epic games store" : "egs_not_official",
"фестиваль keep calm, do games" : "festival",
"elite Dangerous" : "elitedangerous",
"animal crossing" : "animalcrossing",
"coub" : "coub",
"собачичи" : "peseli",
"overwatch" : "overwatch",
"upscale" : "upscale",
"design" : "design",
"wild saloon" : "wildsaloon",
"автоспорт" : "racing",
"vr / ar / mr" : "vr_ar",
"dota" : "dota",
"игры от paradox" : "paradoxgames",
"the division" : "division",
"gog" : "gog_not_official",
"ищу команду" : "findteam",
"world of warshipworld of tanks" : "wot",
"megami tensei" : "megaten",
"таверна" : "taverna",
"arknights" : "arknights",
"dead by daylight" : "dbd"
}
