DTF_TAGS = [
"[Игры](https://dtf.ru/games)",
"[Индустрия](https://dtf.ru/gameindustry)",
"[Гость DTF](https://dtf.ru/guest)",
"[Gamedev](https://dtf.ru/gamedev)",
"[Кино и сериалы](https://dtf.ru/cinema)",
"[Жизнь](https://dtf.ru/life)",
"[Гайды](https://dtf.ru/howto)",
"[Почитать](https://dtf.ru/read)",
"[Железо](https://dtf.ru/hard)",
"[Скидки](https://dtf.ru/sale)",
"[Инди](https://dtf.ru/indie)",
"[Ретро](https://dtf.ru/retro)",
"[Видео и гифки](https://dtf.ru/avi)",
"[Офтоп](https://dtf.ru/flood)",
"[Настолки](https://dtf.ru/boardgames)",
"[Подкасты](https://dtf.ru/podcasts)",
"[Киберспорт](https://dtf.ru/esport)",
"[Конкурс](https://dtf.ru/contest)",
"[Аниме](https://dtf.ru/anime)",
"[Вопросы](https://dtf.ru/ask)",
"[Мобайл](https://dtf.ru/mobile)",
"[Мемы](https://dtf.ru/kek)",
"[no context](https://dtf.ru/nocontext)",
"[Наука](https://dtf.ru/science)",
"[Прямые эфиры](https://dtf.ru/live)",
"[Блогосфера](https://dtf.ru/qat)",
"[Музыка](https://dtf.ru/music)",
"[Творчество](https://dtf.ru/craft)",
"[Ссылки в интернете](https://dtf.ru/nenanimalsia)",
"[Жиза ГД](https://dtf.ru/zhizagd)",
"[Сломалось](https://dtf.ru/bugs)",
"[Ищу пати](https://dtf.ru/party)",
"[Батискаф Подкаст](https://dtf.ru/batiskaf)",
"[Барахолка](https://dtf.ru/barter)",
"[Не занесли](https://dtf.ru/nezanesli)",
"[Скриншоты](https://dtf.ru/screenshots)",
"[Everypod](https://dtf.ru/everypod)",
"[О порно](https://dtf.ru/aboutporn)",
"[Шаурма и друзья](https://dtf.ru/shaurmashaverma)",
"[Unreal Engine](https://dtf.ru/unrealengine)",
"[Фото](https://dtf.ru/photo)",
"[Rainbow Six Siege](https://dtf.ru/r6)",
"[Косплей](https://dtf.ru/s/cosplay)",
"[Unity](https://dtf.ru/s/unity)",
"[Арт](https://dtf.ru/s/art)",
"[Драма 24/7](https://dtf.ru/dramaqueen)",
"[Destiny](https://dtf.ru/destiny)",
"[Хокку и красивые коты](https://dtf.ru/s/cats)",
"[Коллекции](https://dtf.ru/s/collection)",
"[Киноликбез](https://dtf.ru/s/narrative)",
"[Minecraft](https://dtf.ru/s/minecraft)",
"[Battlefield](https://dtf.ru/bf)",
"[PlayStation](https://dtf.ru/s/playstation)",
"[Mordhau](https://dtf.ru/mordhau)",
"[Хакатон](https://dtf.ru/hack)",
"[For Honor](https://dtf.ru/forhonor)",
"[World of Warcraft](https://dtf.ru/s/wow)",
"[Хакатон-2019](https://dtf.ru/hackathon)",
"[Анимация](https://dtf.ru/s/animation)",
"[В предыдущих сериях](https://dtf.ru/s/previous)",
"[Тройное А](https://dtf.ru/triplacast)",
"[Глянец](https://dtf.ru/gloss)",
"[Новости геймдева](https://dtf.ru/s/gamedevnews)",
"[Игры Star Wars](https://dtf.ru/s/starwars)",
"[Epic Games Store](https://dtf.ru/s/egs_not_official)",
"[Фестиваль Keep Calm, Do Games](https://dtf.ru/s/festival)",
"[Elite Dangerous](https://dtf.ru/elitedangerous)",
"[Animal Crossing](https://dtf.ru/s/animalcrossing)",
"[Coub](https://dtf.ru/coub)",
"[Собачичи](https://dtf.ru/s/peseli)",
"[Overwatch](https://dtf.ru/s/overwatch)",
"[Upscale](https://dtf.ru/upscale)",
"[Design](https://dtf.ru/s/design)",
"[Wild Saloon](https://dtf.ru/s/wildsaloon)",
"[Автоспорт](https://dtf.ru/s/racing)",
"[VR / AR / MR](https://dtf.ru/s/vr_ar)",
"[DOTA](https://dtf.ru/s/dota)",
"[Игры от Paradox](https://dtf.ru/s/paradoxgames)",
"[The Division](https://dtf.ru/s/division)",
"[GOG](https://dtf.ru/s/gog_not_official)",
"[Ищу команду](https://dtf.ru/findteam)",
"[World of Warships/World of Tanks](https://dtf.ru/s/wot)",
"[Megami Tensei](https://dtf.ru/s/megaten)",
"[Таверна](https://dtf.ru/s/taverna)",
"[Arknights](https://dtf.ru/s/arknights)",
"[Dead by Daylight](https://dtf.ru/s/dbd)"
]
